swagger: "2.0"
info:
  title: Webo API
  description: Backend for Webo Client
  version: 1.0.0
host: localhost:8080
basePath: /v1
schemes:
  - http
tags:
  - name: Authentication
    description: Everything about authentication and authorization
paths:
  /login:
    post:
      tags:
        - Authentication
      summary: Logs in users.
      description: Logs in users.
      produces:
        - application/json
      parameters:
        - in: body
          name: email
          description: Email of the user
          required: true
          type: string
        - in: body
          name: password
          description: Password of the user
          required: true
          type: string
      responses:
        202:
          description: Accepted
        422:
          description: Unprocessable entity
  /signup:
    post:
      tags:
        - Authentication
      summary: Register users.
      description: Creates new users.
      produces:
        - application/json
      parameters:
        - in: body
          name: email
          description: Email of the user
          required: true
          type: string
        - in: body
          name: handle
          description: Handle of the user
          required: true
          type: string
        - in: body
          name: password
          description: Password of the user
          required: true
          type: string
      responses:
        201:
          description: Created
        400:
          description: Bad request