services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    build:
      context: .
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80

  server:
    container_name: server
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
    ports:
      - 8080:8080
    depends_on:
      - db
      - nginx

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
    restart: always
    depends_on:
      - nginx

  db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
    - POSTGRES_DB=${DB_NAME}
    - POSTGRES_USER=${DB_USER}
    - POSTGRES_PASSWORD=${DB_PASSWORD}

volumes:
  db:
    driver: local